workflows:
  ios-debug:
    name: iOS Debug
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_VERSION: latest
    scripts:
      - name: Install Flutter
        script: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "::add-path::$(pwd)/flutter/bin"
      - name: Install CocoaPods
        script: sudo gem install cocoapods
      - name: Get Flutter Packages
        script: flutter pub get
      - name: Enable VNC Server
        script: |
          brew install vnc-server
          vncserver -localhost no -SecurityTypes None :1
          echo "VNC Server started on port 5901"
      - name: Build and Test
        script: flutter test
